#!bin/bash

git clone https://github.com/sonatype/nexus-book.git
git clone https://github.com/sonatype/JGit.git
git clone https://github.com/sonatype/m2eclipse-book.git
git clone https://github.com/sonatype/maven-guide-en.git
git clone https://github.com/sonatype/maven-guide-de.git
git clone https://github.com/sonatype/maven-guide-zh.git
git clone https://github.com/sonatype/nexus-book-de.git
git clone https://github.com/sonatype/m2eclipse-book-de.git
git clone https://github.com/sonatype/maven-cookbook.git
git clone https://github.com/sonatype/maven-scm-providers-git.git
git clone https://github.com/sonatype/sonatype-bundle-plugin.git
git clone https://github.com/sonatype/sonatype-peaberry.git
git clone https://github.com/sonatype/sonatype-archetype.git
git clone https://github.com/sonatype/maven-example-en.git
git clone https://github.com/sonatype/maven-reference-en.git
git clone https://github.com/sonatype/jgit-simple.git
git clone https://github.com/sonatype/sonatype-tycho.git
git clone https://github.com/sonatype/wagon-jetty.git
git clone https://github.com/sonatype/sshjgit.git
git clone https://github.com/sonatype/m2eclipse-scala.git
git clone https://github.com/sonatype/eclipse-commons.git
git clone https://github.com/sonatype/sonatype-aether.git
git clone https://github.com/sonatype/plexus-utils.git
git clone https://github.com/sonatype/maven-example-fr.git
git clone https://github.com/sonatype/tycho-extras.git
git clone https://github.com/sonatype/nexus-ruby-support.git
git clone https://github.com/sonatype/sample-projects.git
git clone https://github.com/sonatype/sisu-guice.git
git clone https://github.com/sonatype/sisu.git
git clone https://github.com/sonatype/patched-xfire.git
git clone https://github.com/sonatype/munge-maven-plugin.git
git clone https://github.com/sonatype/jetty-test-case.git
git clone https://github.com/sonatype/cometd-asynchttpclient.git
git clone https://github.com/sonatype/simple-example.git
git clone https://github.com/sonatype/jarjar-maven-plugin.git
git clone https://github.com/sonatype/p2-bridge.git
git clone https://github.com/sonatype/sisu-xmlrpc.git
git clone https://github.com/sonatype/plexus-classworlds.git
git clone https://github.com/sonatype/plexus-component-factories.git
git clone https://github.com/sonatype/plexus-components.git
git clone https://github.com/sonatype/plexus-containers.git
git clone https://github.com/sonatype/plexus-pom.git
git clone https://github.com/sonatype/modello.git
git clone https://github.com/sonatype/sisu-encryptor.git
git clone https://github.com/sonatype/wagon-ahc.git
git clone https://github.com/sonatype/maven-demo.git
git clone https://github.com/sonatype/http-testing-harness.git
git clone https://github.com/sonatype/recurly-client-java.git
git clone https://github.com/sonatype/aether-demo-maven-plugin.git
git clone https://github.com/sonatype/m2eclipse-guice.git
git clone https://github.com/sonatype/RestSimple.git
git clone https://github.com/sonatype/plexus-cipher.git
git clone https://github.com/sonatype/plexus-sec-dispatcher.git
git clone https://github.com/sonatype/plexus-interpolation.git
git clone https://github.com/sonatype/plexus-io.git
git clone https://github.com/sonatype/plexus-archiver.git
git clone https://github.com/sonatype/plexus-compiler.git
git clone https://github.com/sonatype/hudson-jsr330.git
git clone https://github.com/sonatype/workout-example.git
git clone https://github.com/sonatype/nexus-rdf-plugin.git
git clone https://github.com/sonatype/sisu-maven-plugin.git
git clone https://github.com/sonatype/AsyncHttpClient-Test-Suite.git
git clone https://github.com/sonatype/tycho-book.git
git clone https://github.com/sonatype/sisu-resource-scanner.git
git clone https://github.com/sonatype/maven-shared.git
git clone https://github.com/sonatype/sisu-mailer.git
git clone https://github.com/sonatype/sisu-sitebricks.git
git clone https://github.com/sonatype/sisu-maven-bridge.git
git clone https://github.com/sonatype/maven-assembly-helpers.git
git clone https://github.com/sonatype/sisu-build-api.git
git clone https://github.com/sonatype/nexus.git
git clone https://github.com/sonatype/sisu-ldap-testsuite.git
git clone https://github.com/sonatype/sisu-jetty-testsuite.git
git clone https://github.com/sonatype/jsw-binaries.git
git clone https://github.com/sonatype/oss-parents.git
git clone https://github.com/sonatype/attach-artifact-maven-plugin.git
git clone https://github.com/sonatype/bundle-publisher-maven-plugin.git
git clone https://github.com/sonatype/cobertura4it-maven-plugin.git
git clone https://github.com/sonatype/emma-maven-plugin.git
git clone https://github.com/sonatype/emma4it-maven-plugin.git
git clone https://github.com/sonatype/findbugs-maven-plugin.git
git clone https://github.com/sonatype/jscoverage-maven-plugin.git
git clone https://github.com/sonatype/maven-crypto-plugin.git
git clone https://github.com/sonatype/maven-properties-plugin.git
git clone https://github.com/sonatype/maven-repository-collector-plugin.git
git clone https://github.com/sonatype/maven-tinkerbell-plugin.git
git clone https://github.com/sonatype/maven-upload-plugin.git
git clone https://github.com/sonatype/maven-version-plugin.git
git clone https://github.com/sonatype/modello-plugin-upgrade.git
git clone https://github.com/sonatype/plx-maven-plugin.git
git clone https://github.com/sonatype/port-allocator-maven-plugin.git
git clone https://github.com/sonatype/provided-dependencies-maven-plugin.git
git clone https://github.com/sonatype/selenium-grid-maven-plugin.git
git clone https://github.com/sonatype/selenium-maven-plugin.git
git clone https://github.com/sonatype/wait-maven-plugin.git
git clone https://github.com/sonatype/yuicompressor-maven-plugin.git
git clone https://github.com/sonatype/shiro.git
git clone https://github.com/sonatype/nexus-request-interceptor-plugin.git
git clone https://github.com/sonatype/nexus-bundle-maker-plugin.git
git clone https://github.com/sonatype/book-site.git

curl "https://api.github.com/orgs/sonatype/repos?per_page=1000" | grep -o 'git@[^"]*' | xargs -L1 git clone
